Social-Network-master/app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from .  import views
from django.contrib.auth.views import (
    login , logout , password_reset ,
     password_reset_done,password_reset_confirm ,password_reset_complete
)

urlpatterns = [
    # url(r'^$', views.home_page , name='home_page'),
    url(r'^login/$',login,{'template_name':'app/login.html'},name='login'),
    url(r'^logout/$',logout,{'template_name':'app/logout.html'},name='logout'),
    # url(r'^app/$', views.home_page,name='home_page'),
    url(r'^SignUp/$',views.SignUp,name='SignUp'),
    url(r'^profile/$', views.profile ,name='profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.profile ,name='profile_with_pk'),

    url(r'^profile/edit-profile/$',views.edit_profile,name='edit_profile'),
    url(r'^change-password/$', views.change_password ,name='password'),

    url(r'^reset-password/$' , password_reset,{'template_name':'app/reset_password.html',
    'post_reset_redirect':'app:password_reset_done','email_template_name':'app/reset_password_email.html'},  name="reset_password"),

    url(r'^reset-password/done/$', password_reset_done,{'template_name': 'app/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm ,{'template_name':'app/reset_password_confirm.html',
    'post_reset_redirect':'app:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset_password/complete/$' ,password_reset_complete , {'template_name':'app/reset_password_complete.html'},name='password_reset_complete')
]


# {'template_name':'app/reset_password.html',
# 'post_reset_redirect':'app:reset_password_done.html',
# 'email_template_name':'app/reset_password_email.html'},
# ,{'template_name':'app/reset_password_done.html'}
# 'email_template_name':'app/reset_password_email.html'

Social-Network-master/mywork/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mywork import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('app/', include('app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.login_redirect, name='login_redirect'),
    url(r'^app/',include(('app.urls', 'app'), namespace='app')),
    url(r'^home/',include(('home.urls', 'home'), namespace='home')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#

Social-Network-master/app/templates/app/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}
  {% block head %}
  <title>home </title>
{% endblock %}

  {% block body %}
  <div class="container">
    <p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" >Save</button>
    </form>

    </p>
  </div>
{% endblock %}

Social-Network-master/app/templates/app/edit_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
  {% block head %}
  <title>home </title>
{% endblock %}

  {% block body %}
  <div class="container">
    <p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" >Save</button>
    </form>

    </p>
  </div>
{% endblock %}

Social-Network-master/app/templates/app/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">


<h1>Log IN!</h1>
<form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >Login</button>
</form>
</div>
{% endblock %}

Social-Network-master/app/templates/app/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">


<h1>Loggeed Out!</h1>
</div>
{% endblock %}

Social-Network-master/app/templates/app/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
  {% block head %}
  <title>home </title>
  <link rel="stylesheet" href="{% static 'app/home.css' %}" type="text/css">
{% endblock %}

  {% block body %}
  <div class="container">
    <h1>Profile</h1>
     <p>Username: {{ user }}</p>
     <p>First name: {{ user.first_name }}</p>
     <p>Last name: {{ user.last_name }}</p>
     <p>Email: {{ user.email }}</p>
     <p>Description: {{ user.userprofile.description }}</p>
     <p>Phone: {{ user.userprofile.phone }}</p>
     <p>City: {{ user.userprofile.city }}</p>
     <p>Website: {{ user.userprofile.website }}</p>
     {% if user.userprofile.image %}
     <img src="{{ user.userprofile.image.url }}" width="240">
     {% endif %}
  </div>
{% endblock %}

Social-Network-master/app/templates/app/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Password Reset</h1>
  <p>Enter your email</p>
<form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >Send</button>
</form>
</div>
{% endblock %}

Social-Network-master/app/templates/app/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        Your Password has been changed
    </p>
    <p><a href="{% url 'app:login' %}">Login</a>
    </p>

</div>
{% endblock %}

Social-Network-master/app/templates/app/reset_password_confirm.html
{% extends 'base.html' %}
{% load staticfiles %}
  {% block head %}
  <title>home </title>
{% endblock %}

  {% block body %}
  <div class="container">
    <p>Reset your password here</p>
    <p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" >Save</button>
    </form>

    </p>
  </div>
{% endblock %}

Social-Network-master/app/templates/app/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

Social-Network-master/app/templates/app/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'app:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}

	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

	{% endautoescape %}

Social-Network-master/app/templates/app/signup.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>SignUp</h1>
<form  method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" >SignUp</button>
</form>

{% endblock %}