Social-Network-master/app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from .  import views
from django.contrib.auth.views import (
    login , logout , password_reset ,
     password_reset_done,password_reset_confirm ,password_reset_complete
)

urlpatterns = [
    # url(r'^$', views.home_page , name='home_page'),
    url(r'^login/$',login,{'template_name':'app/login.html'},name='login'),
    url(r'^logout/$',logout,{'template_name':'app/logout.html'},name='logout'),
    # url(r'^app/$', views.home_page,name='home_page'),
    url(r'^SignUp/$',views.SignUp,name='SignUp'),
    url(r'^profile/$', views.profile ,name='profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.profile ,name='profile_with_pk'),

    url(r'^profile/edit-profile/$',views.edit_profile,name='edit_profile'),
    url(r'^change-password/$', views.change_password ,name='password'),

    url(r'^reset-password/$' , password_reset,{'template_name':'app/reset_password.html',
    'post_reset_redirect':'app:password_reset_done','email_template_name':'app/reset_password_email.html'},  name="reset_password"),

    url(r'^reset-password/done/$', password_reset_done,{'template_name': 'app/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm ,{'template_name':'app/reset_password_confirm.html',
    'post_reset_redirect':'app:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset_password/complete/$' ,password_reset_complete , {'template_name':'app/reset_password_complete.html'},name='password_reset_complete')
]


# {'template_name':'app/reset_password.html',
# 'post_reset_redirect':'app:reset_password_done.html',
# 'email_template_name':'app/reset_password_email.html'},
# ,{'template_name':'app/reset_password_done.html'}
# 'email_template_name':'app/reset_password_email.html'

Social-Network-master/home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views

urlpatterns = [
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friends,
    name='change_friends'),
]

Social-Network-master/mywork/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mywork import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('app/', include('app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.login_redirect, name='login_redirect'),
    url(r'^app/',include(('app.urls', 'app'), namespace='app')),
    url(r'^home/',include(('home.urls', 'home'), namespace='home')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#

Social-Network-master/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>yooohoho</title>
    <!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous"-->

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- <meta name="viewport" content="width=device-width"> -->
    {% block head %}
    {% endblock %}
    <style media="screen">
      #body  {
        padding-top: 50px;
      }
    </style>
  </head>
  <body>
    <div class="container">


    <nav class="navbar navbar-default ">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/app/login">Social Network</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          {% if user.is_authenticated %}

          <ul class="nav navbar-nav navbar-left">
            <li><a href="{% url 'home:home' %}">Home </a></li>
            <li><a href="/app/profile">Profile </a></li>
            <li><a href="/app/change-password">Change Password</a></li>
            <li><a href="{% url 'app:edit_profile' %}">Edit Profile </a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/app/logout">LogOut </a></li>
          </ul>
          {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/app/SignUp"> SignUp  </a></li>

          </ul>
          <ul class="nav navbar-nav navbar-left">
            <li><a href="/app/reset-password"> Reset Password</a></li>

          </ul>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>
</div>
<div id="body"  >
    {% block body %}
    {% endblock %}
  </div>
  </body>
</html>